XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
PROJECT_ROOT=.
PROJECT=$(PROJECT_ROOT)/CustomServiceListener.xcodeproj
TARGET=CustomServiceListener

all: libCustomServiceListenerSDK.a

libCustomServiceListener-i386.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphonesimulator -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphonesimulator/lib$(TARGET).a $@

libCustomServiceListener-armv7.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphoneos -arch armv7 -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphoneos/lib$(TARGET).a $@

libCustomServiceListener-armv7s.a:
	$(XBUILD) -project $(PROJECT) -target $(TARGET) -sdk iphoneos -arch armv7s -configuration Release clean build
	-mv $(PROJECT_ROOT)/build/Release-iphoneos/lib$(TARGET).a $@

libCustomServiceListenerSDK.a: libCustomServiceListener-i386.a libCustomServiceListener-armv7.a libCustomServiceListener-armv7s.a
	lipo -create -output $@ $^

clean:
	-rm -f *.a *.dll