// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Collections.Generic;

namespace testUnwind
{
	public partial class thetableviewController : UIViewController
	{
		public thetableviewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			CreateTableItems();

		}

		protected void CreateTableItems ()
		{
			List<string> tableItems = new List<string> ();
			tableItems.Add ("Vegetables");
			tableItems.Add ("Fruits");
			tableItems.Add ("Flower Buds");
			tableItems.Add ("Legumes");
			tableItems.Add ("Bulbs");
			tableItems.Add ("Tubers");
			table.Source = new testUnwindTableSource(tableItems.ToArray());
		}

	}
}
