#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("LoginScreen.Android.Sample.Resource", IsApplication=true)]

namespace LoginScreen.Android.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LoginScreen.Resource.Drawable.alert = global::LoginScreen.Android.Sample.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::LoginScreen.Android.Sample.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::LoginScreen.Android.Sample.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::LoginScreen.Android.Sample.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::LoginScreen.Android.Sample.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::LoginScreen.Android.Sample.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::LoginScreen.Android.Sample.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::LoginScreen.Android.Sample.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::LoginScreen.Android.Sample.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::LoginScreen.Android.Sample.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::LoginScreen.Android.Sample.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::LoginScreen.Android.Sample.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::LoginScreen.Android.Sample.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::LoginScreen.Android.Sample.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::LoginScreen.Android.Sample.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::LoginScreen.Android.Sample.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::LoginScreen.Android.Sample.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::LoginScreen.Android.Sample.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::LoginScreen.Android.Sample.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::LoginScreen.Android.Sample.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::LoginScreen.Android.Sample.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::LoginScreen.Android.Sample.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::LoginScreen.Android.Sample.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::LoginScreen.Android.Sample.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::LoginScreen.Android.Sample.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::LoginScreen.Android.Sample.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::LoginScreen.Android.Sample.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::LoginScreen.Android.Sample.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::LoginScreen.Android.Sample.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::LoginScreen.Android.Sample.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::LoginScreen.Android.Sample.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::LoginScreen.Android.Sample.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::LoginScreen.Android.Sample.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::LoginScreen.Android.Sample.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::LoginScreen.Android.Sample.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::LoginScreen.Android.Sample.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::LoginScreen.Android.Sample.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::LoginScreen.Android.Sample.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::LoginScreen.Android.Sample.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::LoginScreen.Android.Sample.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::LoginScreen.Android.Sample.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::LoginScreen.Android.Sample.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::LoginScreen.Android.Sample.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::LoginScreen.Android.Sample.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::LoginScreen.Android.Sample.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::LoginScreen.Android.Sample.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::LoginScreen.Android.Sample.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::LoginScreen.Android.Sample.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::LoginScreen.Android.Sample.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::LoginScreen.Android.Sample.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::LoginScreen.Android.Sample.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::LoginScreen.Android.Sample.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_register = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reset = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int divider_bottom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int divider_top = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edittext_bg_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edittext_textcolor_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int image_password = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int image_password_active = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int image_username = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int image_username_active = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int password_right_selector = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int textfield = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int textfield_active = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int username_right_selector = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int bottomSpace = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int confirmPasswordEdit = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int emailEdit = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int errorLayout = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int errorMessage = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int fake = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int forgotLayout = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int forgotText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int loginButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int loginEdit = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int loginLayout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int loginText = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int noAccountImage = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int noAccountSection = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int noAccountText = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int passwordEdit = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int registerButton = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int registerText = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int resetButton = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int resetText = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int rootLayout = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int titleLayout = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_reset = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_validationerror = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
