#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.Data.Droid.Resource", IsApplication=true)]

namespace Xamarin.Data.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Xamarin.Data.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Xamarin.Data.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_refresh_data = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_about = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_about_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_about_unselected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_sessions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sessions_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_sessions_unselected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_speakers = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_speakers_selected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_speakers_unselected = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int aboutwebview = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int headshotImageView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int sessionCountTextView = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int speakerNameTextView = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int twitterTextView = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_with_spinner = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int speaker_row = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f050000
			public const int speaker_sessions = 2131034112;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int activity_about_label = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int activity_sessions_label = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int activity_speakers_label = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int downloading_sessions_json_message = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int downloading_sessions_json_title = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int loading_sessions_json_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int loading_sessions_json_title = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int menu_refresh_data = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
