// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;

namespace Maestro3Mac
{
	public partial class MaestroWorkspaceView : NSView
	{
		public MaestroWorkspaceView (IntPtr handle) : base (handle)
		{
		}

		public override void DrawRect (System.Drawing.RectangleF dirtyRect)
		{
			var bgPath = NSBundle.MainBundle.PathForResource ("grid_square", "png");
			var bgPattern = NSColor.FromPatternImage(new NSImage(bgPath));
			var bgColorPattern = bgPattern.CGColor;
			this.WantsLayer = true;
			this.Layer.BackgroundColor = bgColorPattern;
		}
	}
}
