// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;
using System.Drawing;
using MonoMac.CoreAnimation;

namespace Maestro3Mac
{
	public partial class MenuView : NSView
	{
		#region Fields
		protected bool _MenuOpen = true;
		#endregion

		#region Properties
		public bool MenuOpen{
			get{ return _MenuOpen;}
			set{ _MenuOpen = value;}
		}
		#endregion

		#region Contructors
		public MenuView (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Overrides
		public override void DrawRect (RectangleF dirtyRect)
		{
			this.WantsLayer = true;
			this.Layer.BackgroundColor = HighImpactColors.HIGray06;
			base.DrawRect (dirtyRect);
		}
		#endregion

		#region Methods
		#endregion
	}
}
