// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoMac.Foundation;
using MonoMac.AppKit;
using System.Drawing;
using MonoMac.CoreAnimation;
using MonoMac.CoreGraphics;
using System.Media;

namespace Maestro3Mac
{
	public partial class ToolBarView : NSView
	{
		#region Fields
		protected bool _ToolBarOpen = true;
		#endregion

		#region Properties
		public bool ToolBarOpen
		{
			get{ return _ToolBarOpen; }
			set{ _ToolBarOpen = value; }
		}
		#endregion

		public ToolBarView (IntPtr handle) : base (handle)
		{
		}

		public override void DrawRect (RectangleF dirtyRect)
		{
			this.WantsLayer = true;
			this.Layer.BackgroundColor = HighImpactColors.HIGray05;
			base.DrawRect (dirtyRect);
			Console.WriteLine ("Drawing");
		}
	}
}
