#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("xxx.Android.Resource", IsApplication=true)]

namespace xxx.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LoginScreen.Resource.Drawable.alert = global::xxx.Android.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::xxx.Android.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::xxx.Android.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::xxx.Android.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::xxx.Android.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::xxx.Android.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::xxx.Android.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::xxx.Android.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::xxx.Android.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::xxx.Android.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::xxx.Android.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::xxx.Android.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::xxx.Android.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::xxx.Android.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::xxx.Android.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::xxx.Android.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::xxx.Android.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::xxx.Android.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::xxx.Android.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::xxx.Android.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::xxx.Android.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::xxx.Android.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::xxx.Android.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::xxx.Android.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::xxx.Android.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::xxx.Android.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::xxx.Android.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::xxx.Android.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::xxx.Android.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::xxx.Android.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::xxx.Android.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::xxx.Android.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::xxx.Android.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::xxx.Android.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::xxx.Android.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::xxx.Android.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::xxx.Android.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::xxx.Android.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::xxx.Android.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::xxx.Android.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::xxx.Android.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::xxx.Android.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::xxx.Android.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::xxx.Android.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::xxx.Android.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::xxx.Android.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::xxx.Android.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::xxx.Android.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::xxx.Android.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::xxx.Android.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::xxx.Android.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::xxx.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int cameraBearing = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int mapType = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int uiCompass = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiRotateGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiScrollGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiTiltGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int uiZoomControls = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int uiZoomGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int useViewLifecycle = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int zOrderOnTop = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int common_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_signin_btn_text_light = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_register = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reset = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_disabled_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_disabled_focus_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_disabled_focus_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_disabled_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_focus_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_focus_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_normal_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_normal_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_pressed_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_pressed_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int divider_bottom = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int divider_top = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int edittext_bg_selector = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int edittext_textcolor_selector = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Einstein = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_plusone_medium_off_client = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_plusone_small_off_client = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_plusone_standard_off_client = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_plusone_tall_off_client = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Icon = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int image_password = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int image_password_active = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int image_username = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int image_username_active = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int IMG_0038 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int password_right_selector = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int textfield = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int textfield_active = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int username_right_selector = 2130837558;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int awesomeView = 2131034145;
			
			// aapt resource value: 0x7f050012
			public const int bottomSpace = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int button1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int button2 = 2131034140;
			
			// aapt resource value: 0x7f050016
			public const int confirmPasswordEdit = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int emailEdit = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int errorLayout = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int errorMessage = 2131034138;
			
			// aapt resource value: 0x7f05000d
			public const int fake = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int forgotLayout = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int forgotText = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int loginButton = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int loginEdit = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int loginLayout = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int loginText = 2131034119;
			
			// aapt resource value: 0x7f05001e
			public const int myButton = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int myButton2 = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public const int noAccountImage = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int noAccountSection = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int noAccountText = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int passwordEdit = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int registerButton = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int registerText = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int resetButton = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int resetText = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int rootLayout = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f05001d
			public const int textView1 = 2131034141;
			
			// aapt resource value: 0x7f050013
			public const int titleLayout = 2131034131;
			
			// aapt resource value: 0x7f050020
			public const int webView1 = 2131034144;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_reset = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_validationerror = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AlDialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TestCustomView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001c
			public const int app_name = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int auth_client_needs_enabling_title = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int auth_client_needs_installation_title = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int auth_client_needs_update_title = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int auth_client_play_services_err_notification_msg = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int auth_client_requested_by_msg = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_using_bad_version_title = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_invalid_account_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_invalid_account_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_network_error_text = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_network_error_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_unknown_issue = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_unsupported_date_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_unsupported_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_unsupported_title = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_update_button = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int common_signin_button_text_long = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int hello = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int library_name = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int tag = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int test = 2131099678;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] MapAttrs = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
