// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.CoreAnimation;
using System.Drawing;

namespace CAAnim
{
	public partial class FlashViewController : UIViewController
	{
		public FlashViewController() : base("FlashViewController", null)
		{
		}

		public override void DidReceiveMemoryWarning()
		{
			base.DidReceiveMemoryWarning();
			// Release any cached data, images, etc that aren't in use.
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			// Perform any additional setup after loading the view, typically from a nib.

			// Start the imageView flashing
			// UIImageView (imageView) added in XIB file
			FlashImage(imageView);

		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);
			// Set the time on the time label (lblTime)
			setCurrentTime();
		}

		public override void ViewDidAppear(bool animated)
		{
			// Slide the show time button (btnShowTime) in
			// After the slide in is complete, will set the button flashing slowly
			SlideButtonIn();
		}

		public override void ViewWillDisappear(bool animated)
		{
			base.ViewWillDisappear(animated);
			// Reset the show time button to fully opaque
			btnShowTime.Layer.Opacity = 1.0f;
		}

		public void setCurrentTime()
		{
			NSDate now = DateTime.Now;
			NSDateFormatter dateFormat = new NSDateFormatter();
			dateFormat.TimeStyle = NSDateFormatterStyle.Medium;

			lblTime.Text = dateFormat.StringFor(now);

			// Will spin the time label (lblTime)
			//SpinTimeLabel();
			// Will "bounce" the time label (lblTime) while fading it in and out.
			BounceTimeLabel();
		}

		public void SpinTimeLabel()
		{
			// Create a basic animation
			CABasicAnimation spin = CABasicAnimation.FromKeyPath("transform.rotation");

			spin.AnimationStopped += AnimationStopped;

			// from value is implied
			spin.To = NSNumber.FromDouble(Math.PI * 2);
			spin.Duration = 0.6;

			//Set the timing function
			CAMediaTimingFunction tf = CAMediaTimingFunction.FromName(CAMediaTimingFunction.EaseInEaseOut);
			spin.TimingFunction = tf;

			// Kick off the animation by adding it to the layer
			lblTime.Layer.AddAnimation(spin, "spinAnimation");
		}

		public void BounceTimeLabel()
		{
			// Create key frame animations
			CAKeyFrameAnimation bounce = CAKeyFrameAnimation.GetFromKeyPath("transform");
			CAKeyFrameAnimation fade = CAKeyFrameAnimation.GetFromKeyPath("opacity");

			// Set the event handler for when the animations stop
			bounce.AnimationStopped += AnimationStopped;
			fade.AnimationStopped += AnimationStopped;

			// Create the values the bounce animation will pass through
			CATransform3D forward = CATransform3D.MakeScale(1.3f, 1.3f, 1.0f);
			CATransform3D back = CATransform3D.MakeScale(0.7f, 0.7f, 1.0f);
			CATransform3D forward2 = CATransform3D.MakeScale(1.2f, 1.2f, 1.0f);
			CATransform3D back2 = CATransform3D.MakeScale(0.9f, 0.9f, 1.0f);

			// Create the values the opacity animation will use to transition between
			NSNumber opacity0 = NSNumber.FromFloat(0.0f);
			NSNumber opacity1 = NSNumber.FromFloat(1.0f);

			bounce.Values = new NSObject[] {
				// Start from the default values set in the XIB
				NSValue.FromCATransform3D(CATransform3D.Identity), 
				NSValue.FromCATransform3D(forward), 
				NSValue.FromCATransform3D(back), 
				NSValue.FromCATransform3D(forward2), 
				NSValue.FromCATransform3D(back2),
				// Return to the default values set in the XIB
				NSValue.FromCATransform3D(CATransform3D.Identity)};

			fade.Values = new NSObject[] {
				// Get the starting value form the modal layer
				NSNumber.FromFloat(lblTime.Layer.Opacity), 
				opacity1, 
				opacity0, 
				opacity1, 
				opacity0,
				// Get the ending value from the modal layer
				NSNumber.FromFloat(lblTime.Layer.Opacity)};

			// Set the animation duration
			bounce.Duration = 5.0f;
			fade.Duration = 5.0f;

			// Animate the CALayer of the time label (lblTime)
			lblTime.Layer.AddAnimation(bounce, "bounceAnimation");
			lblTime.Layer.AddAnimation(fade, "fadeAnimation");
		}

		public void SlideButtonIn()
		{
			// Create a basic animation
			CABasicAnimation slide = CABasicAnimation.FromKeyPath("position");

			//Set the starting point for the slide in, from off the left side of the screen
			slide.From = NSValue.FromCGPoint(new PointF(-100.0f, btnShowTime.Layer.Position.Y));
			// Set the destination position, get frmo the modal layer of the show time button (btnShowTime)
			slide.To = NSValue.FromCGPoint(btnShowTime.Layer.Position);
			// How long the slide in will take
			slide.Duration = 1.0f;

			//Set the timing function to ease in/ease out rather than a fully linear animation
			CAMediaTimingFunction tf = CAMediaTimingFunction.FromName(CAMediaTimingFunction.EaseInEaseOut);
			slide.TimingFunction = tf;
			// After slide in is complete, start fading the show time button (btnShowTime) in and out
			slide.AnimationStopped += FadeRepeat;

			// Kick off the animation by adding it to the CALayer
			btnShowTime.Layer.AddAnimation(slide, "slideAnimation");

		}

		public void AnimationStopped(object sender, CAAnimationStateEventArgs e)
		{
			Console.WriteLine("{0} finished {1}", sender, e.Finished);
		}

		public void FadeRepeat(object sender, CAAnimationStateEventArgs e)
		{
			//btnShowTime.Layer.RemoveAnimation("fadeInOUt");
			// Create a key frame animation
			CAKeyFrameAnimation fade = CAKeyFrameAnimation.GetFromKeyPath("opacity");

			// Set the opacities between which the show time button will cycle
			NSNumber opacity0 = NSNumber.FromFloat(0.0f);
			NSNumber opacity1 = NSNumber.FromFloat(1.0f);
			fade.Values = new NSObject[] {
				opacity1,
				opacity0,
				opacity1,
			};

			// Set the flashing speed
			fade.Duration = 1.0f;
			// Set hoew long the flashing will repeat for
			fade.RepeatDuration= 1000.0;

			// Add the animation to the show time button (btnShowTime) CALayer
			btnShowTime.Layer.AddAnimation(fade, "fadeInOut");
		}

		public void FlashImage(UIImageView iv)
		{
			// Create a key frame animation
			CAKeyFrameAnimation flash = CAKeyFrameAnimation.GetFromKeyPath("opacity");

			// Set the opacities between which the image view (iv) will cycle
			NSNumber opacity0 = NSNumber.FromFloat(0.1f);
			NSNumber opacity1 = NSNumber.FromFloat(1.0f);
			flash.Values = new NSObject[] {
				opacity1,
				opacity0,
				opacity1,
			};

			// Set the flashing speed
			flash.Duration = 2.0f;
			// Set hoew long the flashing will repeat for
			flash.RepeatDuration= 1000.0;


			// Add the animation to the imageView CALayer
			iv.Layer.AddAnimation(flash, "fadeInOut");
		}
	}
}
